### auth - signin
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "signup@test.com",
  "password": "1q2w3e4r"
}

### auth - signin, form
POST http://localhost:8080/auth/login
Content-Type: application/x-www-form-urlencoded

username=signup@test.com&password=1q2w3e4r


### signup
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "name": "signup-test",
  "email": "signup@test.com",
  "password": "1q2w3e4r"
}

### user page
GET http://localhost:8080/user

### admin page
GET http://localhost:8080/admin