### auth - signin
POST https://falsystack.jp/auth/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "1q2w3e4r"
}

### auth - signin, form
POST http://localhost:8080/auth/login
Content-Type: application/x-www-form-urlencoded

username=signup@test.com&password=1q2w3e4r


### signup
#POST http://localhost:8080/auth/signup
POST https://falsystack.jp/auth/signup
Content-Type: application/json

{
  "name": "test-user",
  "email": "test@test.com",
  "password": "1q2w3e4r"
}

### user page
GET http://localhost:8080/user

### admin page
GET http://localhost:8080/admin