### Post-Create
POST http://localhost:8080/post
Content-Type: application/json
#Set-Cookie: SESSION=4b3e264d-1f05-40ba-9e4f-082a4bb4a01d
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzAxMDEyNzkxfQ.kncubajJtz1y-jGwGqqbk_x6vhqxYOSSzDR8siWp3II

{
  "author": "daum",
  "content": "test test test3",
  "hashTags": "#javascript#nextjs#java",
  "title": "test1"
}

### Post-Detail
GET http://localhost:8080/post/2
Content-Type: application/json
Authorization: ""